//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGlovo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int IDCliente { get; set; }
        public string NombreCliente { get; set; }
        public string Correo { get; set; }
        public string Contraseña { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Telefono { get; set; }
    }
}
